#Regenerar o /minerar
on server start:
    set {MinerarFechado} to true
    wait 20 seconds
    make console execute command "/mv regen minerar"
    make console execute command "/mv confirm"
    wait 30 seconds
    set {MinerarFechado} to false
#/minerar fechado
on command "/mina":
    if {MinerarFechado} is true:
        cancel event 
        send "&cO mundo de mineraçao esta fechado para o reset."
        send "&3Espere um pouco para minerar."
        stop